# Generated by Django 3.2.15 on 2022-08-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='yera',
            new_name='year',
        ),
    ]
